ocfs2: remove two unused variables
A reliability fix introduced two local variables but never used
them:

fs/ocfs2/dlm/dlmrecovery.c: In function 'dlm_free_dead_locks':
fs/ocfs2/dlm/dlmrecovery.c:2306:6: error: unused variable 'i' [-Werror=unused-variable]
fs/ocfs2/dlm/dlmrecovery.c:2305:20: error: unused variable 'queue' [-Werror=unused-variable]

This removes them both again.

Link: http://lkml.kernel.org/r/20170824222149.759050-1-arnd@arndb.de
Fixes: d09f2c6cf3b8 ("ocfs2: re-queue AST or BAST if sending is failed to improve the reliability")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Changwei Ge <ge.changwei@h3c.com>
Cc: Mark Fasheh <mfasheh@versity.com>
Cc: Joel Becker <jlbec@evilplan.org>
Cc: Junxiao Bi <junxiao.bi@oracle.com>
Cc: Joseph Qi <jiangqi903@gmail.com>
Cc: "Gang He" <ghe@suse.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>