mm-change-the-call-sites-of-numa-statistics-items-checkpatch-fixes
ERROR: "foo * bar" should be "foo *bar"
#249: FILE: include/linux/vmstat.h:222:
+extern void __inc_numa_state(struct zone * zone,

WARNING: line over 80 characters
#402: FILE: mm/vmstat.c:768:
+	changes += fold_diff(global_zone_diff, global_numa_diff, global_node_diff);

WARNING: Missing a blank line after declarations
#459: FILE: mm/vmstat.c:862:
+			int v = pset->vm_numa_stat_diff[i];
+			pset->vm_numa_stat_diff[i] = 0;

ERROR: space required before the open parenthesis '('
#571: FILE: mm/vmstat.c:1641:
+	for(i = 0; i < NR_VM_NUMA_STAT_ITEMS; i++)

WARNING: line over 80 characters
#588: FILE: mm/vmstat.c:1752:
+				__func__, vmstat_text[i + NR_VM_ZONE_STAT_ITEMS], val);

total: 2 errors, 4 warnings, 460 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-change-the-call-sites-of-numa-statistics-items.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Kemi Wang <kemi.wang@intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>